#ifndef INSPANGENERATOR
#define INSPANGENERATOR

#include "FeatureGeneratorAdapter.h"
#include "../tools/namefind/TokenNameFinder.h"
#include "../tools/util/Span.h"
#include <string>
#include <vector>

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreemnets.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


namespace opennlp
{
    namespace tools
    {
        namespace util
        {
            namespace featuregen
            {


                using opennlp::tools::namefind::TokenNameFinder;
                using opennlp::tools::util::Span;

                /// <summary>
                /// Generates features if the tokens are recognized by the provided
                /// <seealso cref="TokenNameFinder"/>.
                /// </summary>
                class InSpanGenerator : public FeatureGeneratorAdapter
                {

              private:
                  const std::string prefix;

                  TokenNameFinder *const finder;

//ORIGINAL LINE: private String currentSentence[];
//JAVA TO C++ CONVERTER WARNING: Since the array size is not known in this declaration, Java to C++ Converter has converted this array to a pointer.  You will need to call 'delete[]' where appropriate:
                  std::string *currentSentence;

//ORIGINAL LINE: private opennlp.tools.util.Span currentNames[];
//JAVA TO C++ CONVERTER WARNING: Since the array size is not known in this declaration, Java to C++ Converter has converted this array to a pointer.  You will need to call 'delete[]' where appropriate:
                  Span *currentNames;

                  /// <summary>
                  /// Initializes the current instance. 
                  /// </summary>
                  /// <param name="prefix"> the prefix is used to distinguish the generated features
                  /// from features generated by other instances of <seealso cref="InSpanGenerator"/>s. </param>
                  /// <param name="finder"> the <seealso cref="TokenNameFinder"/> used to detect the names. </param>
              public:
                  InSpanGenerator(const std::string &prefix, TokenNameFinder *finder);

                  virtual void createFeatures(std::vector<std::string> &features, std::string tokens[], int index, std::string preds[]);
                };

            }
        }
    }
}


#endif	//#ifndef INSPANGENERATOR
